version: '2'
services:
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    image: microservice/config-server
    networks:
      - config-net
    ports:
      - "9009:9009"
  
  eureka-server-peer1:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    image: microservice/eureka-server-peer1
    networks: 
      - eureka-net
    expose:
      - "3333"
    ports:
      - "3333:3333"
    environment:
      - spring.profiles.active=peer1
    
#  eureka-server-peer2:
#    build:
#      context: ./eureka-server
#      dockerfile: Dockerfile
#    image: microservice/eureka-server-peer2
#    networks: 
#      - eureka-net
#    expose:
#      - "4444"
#    ports:
#      - "4444:4444"
#    environment:
#      - spring.profiles.active=peer2
  
#  eureka-server-peer3:
#    build:
#      context: ./eureka-server
#      dockerfile: Dockerfile
#    image: microservice/eureka-server-peer3
#    networks: 
#      - eureka-net
#    expose:
#      - "5555"
#    ports:
#      - "5555:5555"
#    environment:
#      - spring.profiles.active=peer3
      
  service-hi:
    build:
      context: ./service-hi
      dockerfile: Dockerfile
    image: microservice/service-hi
    depends_on:
      - config-server
    networks:
      - config-net
      - eureka-net
    ports:
      - "8000:8000"
    restart: always
      
  service-ribbon:
    build:
      context: ./service-ribbon
      dockerfile: Dockerfile
    image: microservice/service-ribbon
    depends_on:
      - config-server
    networks:
      - config-net
      - eureka-net
    ports:
      - "9000:9000"
    restart: always
    
networks:
  config-net:
    driver: bridge
  eureka-net:
    driver: bridge
 
