config-server:
  image: microservice/config-server
  ports:
    - "9009:9009"

eureka-server:
  image: microservice/eureka-server
  ports:
    - "3333:3333"

service-hi:
  image: microservice/service-hi
  ports:
    - "8000:8000"
  links:
    - "config-server"
    - "eureka-server"
    
service-ribbon:
  image: microservice/service-ribbon
  ports:
    - "9000:9000"
  links:
    - "config-server"
    - "eureka-server"
