logging:
  level:
    org.springframework.cloud.gateway: debug

spring:
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbit:
    host: localhost
    port: 15672
    username: admin
    password: admin
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
      cors:
        allowed-origins: "*"
        allowed-methods: "*"