server:
  port: 9000
spring:
  zipkin:
    base-url: http://localhost:9411/
ribbon:
  eager-load:
    enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka111@peer1:3333/eureka/,http://eureka:eureka111@peer2:4444/eureka/,http://eureka:eureka111@peer3:5555/eureka/