spring:
  application:
    name: eureka-server
  security:
    basic:
      enabled: true
    user:
      name: eureka
      password: eureka111
---
spring:
  profiles: peer1
server:
  port: 3333
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:eureka111@peer2:4444/eureka/,http://eureka:eureka111@peer3:5555/eureka/
---
spring:
  profiles: peer2
server:
  port: 4444
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka111@peer1:3333/eureka/,http://eureka:eureka111@peer3:5555/eureka/
---
spring:
  profiles: peer3
server:
  port: 5555
eureka:
  instance:
    hostname: peer3
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka111@peer1:3333/eureka/,http://eureka:eureka111@peer2:4444/eureka/